title: "Ernest Elnino"
author: "Protocol Whisperer"
description: "TLDR by Er<b style=\"color: #f45;\">n</b>est <b style=\"color: #f45;\">Odhi</b>ambo Elnino"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "README.md", title: "Home"}
  - {file: "blog.md", title: "Blog"}
  - {file: "", title: "Lab"}
  - {file: "about.md", title: "About"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ernest.odhiambo1@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/ProtocolWhisperer01"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/ElninoErnest"}
  - {title: Medium, icon: medium, url: "https://medium.com/@protocolwhodis01"}
  - {title: Linkedin, icon: linkedin, url: "https://linkedin.com/in/ernest-odhiambo-elnino-6475a2161"}

extra_css:
  - {file: "extra.css"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
